- name: Downloading node-exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /root/

- name: Extracting node_exporter-1.8.1.linux-amd64.tar.gz
  ansible.builtin.unarchive:
    src: /root/node_exporter-1.8.1.linux-amd64.tar.gz
    dest: /root/
    remote_src: yes
- name: Copy files from foo to bar
  ansible.builtin.copy:
    src: /root/node_exporter-1.8.1.linux-amd64/node_exporter
    dest: /usr/local/bin/
    mode: 0766
    remote_src: yes	
- name: Copy files from foo to bar
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    system: true		
- name: Creating systemd service
  ansible.builtin.template:
    src: "{{node}}"
    dest: /etc/systemd/system/node_exporter.service
    owner: node_exporter
    group: node_exporter
    mode: 0644
- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: "Starting node-exporter service"
  service:
    name: node_exporter
    state: started
