- name: debian os update
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
- name: debian os upgrade
  apt:
    state: latest
    force_apt_get: yes
    cache_valid_time: 3600
- name: installing jenkins
  apt:
    name: "{{jenkins}}"
    state: latest

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present


